src/accounts/urls.py
from django.urls import path

from accounts.views import (
    AccountCreateView,
    AccountLoginView,
    AccountLogoutView,
    AccountPasswordUpdateView,
    AccountUpdateView,
    LeaderboardView,
    LeaderboardStatsView,
    ContactUsView
)

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPasswordUpdateView.as_view(), name='password'),
    path('leaderboard/', LeaderboardView.as_view(), name='leaderboard'),
    path('statistics/', LeaderboardStatsView.as_view(), name='statistics'),
    path('contact_us/', ContactUsView.as_view(), name='contact_us'),
]

src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from quiz.views import bitcoin, normalize

API_PREFIX = 'api/v1'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),

    path('accounts/', include('accounts.urls')),
    path('quizes/', include('quiz.urls')),

    path(f'{API_PREFIX}/', include('quiz.api.urls')),
    path(f'{API_PREFIX}/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_PREFIX}/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('bitcoin/', bitcoin),
    path('normalize/', normalize),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    class Meta:
        permissions = [('view_stats', 'View statistics')]

    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    rating = models.PositiveSmallIntegerField(null=True, default=0, validators=[MaxValueValidator(100)])
    image = models.ImageField(null=True, default='default.jpg', upload_to='pics')

    def save(self, *args, **kwargs):
        print(self.full_clean())
        super().save(*args, **kwargs)

src/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm, fields, forms, Form

from django import forms

from accounts.models import User


class AccountCreateForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
        ]


class AccountUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'bio',
            'birth_date',
        ]


class ContactUs(Form):
    subject = fields.CharField(max_length=256, empty_value='Message from Testify')
    message = fields.CharField(widget=forms.Textarea)

src/accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.core.mail import send_mail
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView, FormView
from django.views.generic.list import ListView

from accounts.forms import AccountCreateForm, AccountUpdateForm, ContactUs
from accounts.models import User


class AccountCreateView(CreateView):
    model = User
    template_name = 'registration.html'
    form_class = AccountCreateForm
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.info(self.request, "New user has just been created!")
        return result


class AccountLoginView(LoginView):
    template_name = 'login.html'

    def get_redirect_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        return reverse('index')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.info(self.request, f'User {self.request.user} has been successfully logged in!')
        return result


class AccountLogoutView(LogoutView):
    template_name = 'logout.html'

    def get(self, request, *args, **kwargs):
        result = super().get(request, *args, **kwargs)
        messages.info(self.request, f'User {self.request.user} has been logged out!')
        return result


class AccountUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'profile.html'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('index')
    paginate_by = 5

    def get_object(self, queryset=None):
        return self.request.user


class AccountPasswordUpdateView(LoginRequiredMixin, PasswordChangeView):
    model = User
    template_name = 'password.html'
    success_url = reverse_lazy('accounts:login')


class LeaderboardView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'leaderboard.html'
    context_object_name = 'users'


class LeaderboardStatsView(PermissionRequiredMixin, LoginRequiredMixin, DetailView):
    permission_required = ['accounts.view_stats']
    model = User

    def get(self, request):
        return HttpResponse('EXTENDED STATS')


class ContactUsView(LoginRequiredMixin, FormView):
    template_name = 'contact_us.html'
    success_url = reverse_lazy('index')
    form_class = ContactUs

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            send_mail(
                subject=form.cleaned_data['subject'],
                message=form.cleaned_data['message'],
                from_email=request.user.email,
                recipient_list=settings.EMAIL_HOST_RECIPIENT.split(':'),
                fail_silently=False,
            )
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

src/accounts/templates/contact_us.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
        <h1>Contact Us</h1>
{% endblock %}

{% block content %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <div class="mt-3">
            <input class="btn btn-success" type="submit" value="Send a message">
            <a class="btn btn-light" href="{% url 'index' %}">Home</a>
        </div>
    </form>
{% endblock %}

src/accounts/templates/leaderboard.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <h1>Leaderboard</h1>
{% endblock %}

{% block content %}
    {% if users %}
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                  <th>#</th>
                  <th>Image</th>
                  <th>Full name</th>
                  <th>Rating</th>
{#                  {% if perms.accounts.view_stats %}#}
                        <th>More...</th>
{#                  {% endif %}#}

                </tr>
            </thead>

            {% for user in users %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><img class="rounded-circle p-1 m-1" width="40" height="40"  src="{{ user.image.url }}"></td>
                    <td> {{ user.username    }}</td>
                    <td> {{ user.rating }}</td>
{#                    {% if perms.accounts.view_stats %}#}
                        <th><a href="{% url 'accounts:statistics' %}"> STATS</a></th>
{#                    {% endif %}#}

                </tr>
            {% endfor %}
        </table>

        <div class="p-1 m-1">
            {% include 'includes/pagination.html' %}
        </div>
    {% else %}
        <p>No users yet :(</p>
    {% endif %}

{% endblock %}

src/accounts/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
        <h1>Log in as a user</h1>
{% endblock %}

{% block content %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <div class="mt-3">
            <input class="btn btn-success" type="submit" value="Log in">
            <a class="btn btn-light" href="{% url 'index' %}">Home</a>
        </div>
    </form>
{% endblock %}

src/accounts/templates/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
        <h1>User is logged out</h1>
{% endblock %}

{% block content %}
        <a class="btn btn-light" href="{% url 'accounts:login' %}">Login</a>
        <a class="btn btn-light" href="{% url 'index' %}">Home</a>
{% endblock %}

src/accounts/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
        <h1>Edit user</h1>
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">

        <div class="media">
            <div class="img-circle.vert">
                <img class="rounded-circle p-1 m-1" width="200" height="200"  src="{{ user.image.url }}">
            </div>
    {#        <img class="rounded-circle p-1 m-1" width="300" height="{{ user.profile.image.height }}"  src="{{ user.profile.image.url }}">#}
    {#        <img class="img-circle p-1 m-1"  src="{{ user.profile.image.url }}">#}
            <div class="media-body  p-3 m-3">
                <h2 class="account-heading">{{ user.username }}</h2>
                <h3 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h3>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>

        {% csrf_token %}

        {{form|crispy}}
{#        <div class = 'mb-3'>#}
{#            Raw passwords are not stored, you can change the password <a href="{% url 'accounts:password' %}">this form</a>#}
{#        </div>#}
{#        {{profile_form|crispy}}#}

{#        <table class="table table-hover p-1 m-3 mb-5">#}
{#            <thead class="thead-dark">#}
{#                <tr>#}
{#                  <th>#</th>#}
{#                  <th>Name</th>#}
{#                  <th>Date</th>#}
{#                  <th>Time spent</th>#}
{#                  <th>Points</th>#}
{#                </tr>#}
{#            </thead>#}
{##}
{#            {% for result in object_list %}#}
{##}
{#                <tr>#}
{#                   <td>{{ forloop.counter}}</td>#}
{#                   <td>{{ result.user.username }}</td>#}
{#                   <td>{{ result.write_date }}</td>#}
{#                   <td>{{ result.time_spent }}</td>#}
{#                   <td>{{ result.points }}</td>#}
{#                </tr>#}
{##}
{#            {% endfor %}#}
{#        </table>#}
{##}
{#        <div class="p-1 m-1">#}
{#            {% include 'includes/pagination.html' %}#}
{#        </div>#}

        <input class="btn btn-success" type="submit" value="Save">
        <a class="btn btn-light" href="{% url 'index' %}">Cancel</a>
    </form>
{% endblock %}

src/accounts/templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
        <h1>Register new user</h1>
{% endblock %}

{% block content %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <input class="btn btn-success" type="submit" value="Register">
        <a class="btn btn-light" href="{% url 'index' %}">Home</a>
    </form>
{% endblock %}